# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2948e78093df4a97192f0b39d06fb63e06fb8533bbd8f2c718648c8fa49e5cc00b4ef5061f13d7b8d94c74c224caa9f0e5c40a08360fd5d060cd791361ad288e

test:
  secret_key_base: 57c561a517b0489db0327b757721e4ea14ba291f2ec6c3e532828d2be0de119609c2ec9c92fed0ca1d8b7046fb9c22c7a792b38e6c6a9ed7126ea9c96a370329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
